# Generated by Django 3.0.3 on 2020-10-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('user_email', models.EmailField(max_length=64)),
                ('user_pw', models.CharField(max_length=64)),
            ],
        ),
    ]
