# Generated by Django 3.1.2 on 2020-10-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TOURLIST_SITE',
            fields=[
                ('tour_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('cat1', models.CharField(max_length=3)),
                ('cat2', models.CharField(max_length=5)),
                ('cat3', models.CharField(max_length=9)),
                ('areacode', models.IntegerField(default=0)),
                ('addr1', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=31)),
                ('mapx', models.FloatField(default=0.0)),
                ('mapy', models.FloatField(default=0.0)),
                ('firstimage', models.CharField(max_length=255)),
                ('firstimage2', models.CharField(max_length=255)),
                ('contentid', models.IntegerField()),
                ('contenttypeid', models.IntegerField()),
                ('readcount', models.IntegerField(default=0)),
                ('sigungucode', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField(default=0)),
            ],
        ),
    ]
