# Generated by Django 3.1.2 on 2020-10-21 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourlistSite',
            fields=[
                ('tour_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('cat1', models.CharField(max_length=3)),
                ('cat2', models.CharField(max_length=5)),
                ('cat3', models.CharField(max_length=9)),
                ('areacode', models.IntegerField(blank=True, null=True)),
                ('addr1', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=31, null=True)),
                ('mapx', models.FloatField()),
                ('mapy', models.FloatField()),
                ('firstimage', models.CharField(blank=True, max_length=255, null=True)),
                ('firstimage2', models.CharField(blank=True, max_length=255, null=True)),
                ('contentid', models.IntegerField()),
                ('contenttypeid', models.IntegerField()),
                ('readcount', models.IntegerField(blank=True, null=True)),
                ('sigungucode', models.IntegerField(blank=True, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tourlist_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TourlistTraffic',
            fields=[
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tour.tourlistsite')),
                ('congestion_1', models.IntegerField()),
                ('congestion_2', models.IntegerField()),
                ('congestion_3', models.IntegerField()),
                ('congestion_4', models.IntegerField()),
                ('congestion_avg', models.FloatField()),
                ('congestion_max', models.FloatField()),
                ('road_count', models.IntegerField()),
                ('measured_at', models.CharField(max_length=31)),
            ],
            options={
                'db_table': 'tourlist_traffic',
                'managed': False,
            },
        ),
    ]
