# Generated by Django 3.0.3 on 2020-10-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourlistsite',
            table='TOURLIST_SITE',
        ),
        migrations.AlterModelTable(
            name='tourlisttraffic',
            table='TOURLIST_TRAFFIC',
        ),
    ]
