# Generated by Django 3.0.3 on 2020-09-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('user_pw', models.CharField(max_length=200)),
                ('user_sex', models.CharField(max_length=200)),
                ('user_age', models.CharField(max_length=200)),
                ('user_add', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=100)),
                ('user_fav_spot1', models.CharField(max_length=100)),
                ('user_fav_spot2', models.CharField(max_length=100)),
                ('user_fav_spot3', models.CharField(max_length=100)),
            ],
        ),
    ]
