# Generated by Django 3.1.2 on 2020-11-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourlistuser',
            table='TOURLIST_USER',
        ),
    ]
