# Generated by Django 3.0.8 on 2020-10-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr1', models.CharField(max_length=255)),
                ('areacode', models.CharField(max_length=255)),
                ('cat1', models.CharField(max_length=255)),
                ('cat2', models.CharField(max_length=255)),
                ('cat3', models.CharField(max_length=255)),
                ('contentid', models.IntegerField(max_length=255)),
                ('contenttypeid', models.IntegerField(max_length=255)),
                ('createdtime', models.IntegerField(max_length=255)),
                ('firstimage', models.CharField(max_length=255)),
                ('firstimage2', models.CharField(max_length=255)),
                ('mapx', models.IntegerField(max_length=255)),
                ('mapy', models.IntegerField(max_length=255)),
                ('mlevel', models.IntegerField(max_length=255)),
                ('modifiedtime', models.IntegerField(max_length=255)),
                ('readcount', models.IntegerField(max_length=255)),
                ('sigungucode', models.IntegerField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
            ],
        ),
    ]
