# Generated by Django 3.0.8 on 2020-10-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourinfo',
            name='mapx',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tourinfo',
            name='mapy',
            field=models.CharField(max_length=255),
        ),
    ]
