# Generated by Django 3.0.8 on 2020-10-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20201004_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourinfo',
            name='addr1',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='tourinfo',
            name='contentid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourinfo',
            name='contenttypeid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourinfo',
            name='createdtime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourinfo',
            name='mlevel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourinfo',
            name='modifiedtime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourinfo',
            name='readcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourinfo',
            name='sigungucode',
            field=models.IntegerField(),
        ),
    ]
