# Generated by Django 3.1.1 on 2020-10-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False, verbose_name='account_id')),
                ('user_id', models.CharField(max_length=20)),
                ('user_pw', models.CharField(max_length=16)),
                ('user_name', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=16)),
                ('gender', models.IntegerField(default=None, max_length=1)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
