# Generated by Django 3.1.2 on 2020-10-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TOURLIST_USER',
            fields=[
                ('user_id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=63)),
                ('user_name', models.CharField(max_length=31)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=63)),
                ('address', models.CharField(max_length=255)),
                ('gps_x', models.FloatField(default=0.0)),
                ('gps_y', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TOURLIST_USER',
            },
        ),
    ]
