# Generated by Django 3.1.2 on 2020-10-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourlistUser',
            fields=[
                ('user_id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=63)),
                ('user_name', models.CharField(max_length=31)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=63)),
                ('address', models.CharField(max_length=255)),
                ('gps_x', models.FloatField()),
                ('gps_y', models.FloatField()),
                ('create_at', models.DateTimeField(db_column='CREATE_at')),
            ],
            options={
                'db_table': 'tourlist_user',
                'managed': False,
            },
        ),
    ]
