# Generated by Django 3.0.3 on 2020-10-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourlistuser',
            table='TOURLIST_USER',
        ),
    ]
