# Generated by Django 3.1.1 on 2020-10-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='gender',
            field=models.IntegerField(default=None),
        ),
    ]
